---
# tasks file for pve_purge
- name: Get guest info to check whether the vmid exists.
  community.general.proxmox_vm_info:
    node: "{{ pve_api_node }}"
    api_user: "{{ pve_api_user }}"
    api_password: "{{ pve_api_password }}"
    api_host: "{{ pve_api_host }}"
    vmid: "{{ vmid }}"
  register: guest_info
